services:
  - type: web
    name: kepswell-etl-api
    runtime: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan storage:link || true
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan migrate --force
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://kepswell-etl-api.onrender.com
      - key: APP_KEY
        generateValue: true
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: pgsql
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: kepswell_etl
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: 2252